package com.parqueaderoiud.autos_col.frames;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Dvn
 */
public class Sal extends javax.swing.JPanel {

	/**
	 * Creates new form Sal
	 */
	public Sal() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpSalida = new javax.swing.JPanel();
        jlCedula = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlModelo = new javax.swing.JLabel();
        jlPlaca = new javax.swing.JLabel();
        jlColor = new javax.swing.JLabel();
        jlCelda = new javax.swing.JLabel();
        jlHoraIn = new javax.swing.JLabel();
        jlFechaSal = new javax.swing.JLabel();
        jlTarifaxHora = new javax.swing.JLabel();
        jlConsecutivo = new javax.swing.JLabel();
        jtxtCedula = new javax.swing.JTextField();
        jtxtNombre = new javax.swing.JTextField();
        jtxtPlaca = new javax.swing.JTextField();
        jtxtModelo = new javax.swing.JTextField();
        jtxtColor = new javax.swing.JTextField();
        jtxtCelda = new javax.swing.JTextField();
        jtxtFechaSal = new javax.swing.JTextField();
        jtxtHoraIn = new javax.swing.JTextField();
        jtxtTarifaxHora = new javax.swing.JTextField();
        jtxtConsecutivo = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpSalida.setBackground(new java.awt.Color(255, 255, 255));
        jpSalida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlCedula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCedula.setText("Cedula");
        jpSalida.add(jlCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 20, 72, -1));

        jlNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNombre.setText("Nombre");
        jpSalida.add(jlNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 47, 72, -1));

        jlModelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlModelo.setText("Modelo");
        jpSalida.add(jlModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 74, 72, -1));

        jlPlaca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPlaca.setText("Placa");
        jpSalida.add(jlPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 104, 72, -1));

        jlColor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlColor.setText("Color");
        jpSalida.add(jlColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 135, 72, -1));

        jlCelda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCelda.setText("#Celda");
        jpSalida.add(jlCelda, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 166, 72, -1));

        jlHoraIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlHoraIn.setText("Hora salida");
        jpSalida.add(jlHoraIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 228, 72, -1));

        jlFechaSal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlFechaSal.setText("Fecha salida");
        jpSalida.add(jlFechaSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 197, 72, -1));

        jlTarifaxHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTarifaxHora.setText("Tarifa por hora");
        jpSalida.add(jlTarifaxHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 262, -1, -1));

        jlConsecutivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlConsecutivo.setText("Consecutivo");
        jpSalida.add(jlConsecutivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 296, 72, -1));

        jtxtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCedulaActionPerformed(evt);
            }
        });
        jpSalida.add(jtxtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 17, 159, -1));
        jpSalida.add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 44, 159, -1));
        jpSalida.add(jtxtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 71, 159, -1));
        jpSalida.add(jtxtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 101, 159, -1));
        jpSalida.add(jtxtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 132, 159, -1));
        jpSalida.add(jtxtCelda, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 166, 159, -1));
        jpSalida.add(jtxtFechaSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 197, 159, -1));
        jpSalida.add(jtxtHoraIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 228, 159, -1));
        jpSalida.add(jtxtTarifaxHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 259, 159, -1));
        jpSalida.add(jtxtConsecutivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 290, 159, -1));

        add(jpSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 400));
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCedulaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlCedula;
    private javax.swing.JLabel jlCelda;
    private javax.swing.JLabel jlColor;
    private javax.swing.JLabel jlConsecutivo;
    private javax.swing.JLabel jlFechaSal;
    private javax.swing.JLabel jlHoraIn;
    private javax.swing.JLabel jlModelo;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlPlaca;
    private javax.swing.JLabel jlTarifaxHora;
    private javax.swing.JPanel jpSalida;
    private javax.swing.JTextField jtxtCedula;
    private javax.swing.JTextField jtxtCelda;
    private javax.swing.JTextField jtxtColor;
    private javax.swing.JTextField jtxtConsecutivo;
    private javax.swing.JTextField jtxtFechaSal;
    private javax.swing.JTextField jtxtHoraIn;
    private javax.swing.JTextField jtxtModelo;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtPlaca;
    private javax.swing.JTextField jtxtTarifaxHora;
    // End of variables declaration//GEN-END:variables
}
